### ISSUE TITLE
Nep VIIR PC get VR events texts

### ISSUE THREAD

**Issue by D3fau4** [u3shit/neptools#20]
Hello!!! I was reading this two Issues (#16 and #17) because i want translate the VR events of Nep: VIIR, i compiled your tool and i get some texts but i cant found the dialogs of the VR events. I checked the EXE in case was there but not, you will have already been able to check some CL3 gives an error like: "MAIN.DAT no found" i know that error is beacuse it dont have any text but someone CL3's have text but it give this error: 

![image](https://user-images.githubusercontent.com/19638408/113487018-e5c7cc80-94b5-11eb-90b9-687f4abee175.png)

when it have text

![image](https://user-images.githubusercontent.com/19638408/113487267-6c30de00-94b7-11eb-9bb7-2e937192a70a.png)

But also I haven't found any of the dialogs of the VR events with your program and in hex. I also see many gbin's, it only extracts an EOF but I think that doesnt matter.
I would appreciate your help and see if we can find those texts.

some cl3's with text: 
[GxArchivedFile063.dat.zip](https://github.com/u3shit/neptools/files/6253183/GxArchivedFile063.dat.zip)

**Comment by u3shit** [comment]
I've checked that "You've cleared the game!" in 03350.cl3, does it change if you change it with a hex editor? Because from a quick look, it looks like it's in an unused section (there are a lot of unused shit copy-pasted into every cl3 file, and it looks like it's one of those, and you have to figure out which single one of the 2000 copies you have to change).
Also pushed a commit to no longer require a gbnl when exporting to lua. However, the lua files won't be pretty.

**Comment by D3fau4** [comment]
Well I haven't seen it, I'm still thinking about translating the full game so i dont check that. So my main question I already solved it
the subtitles of the vr events are those .TEX (03892.tex - 05456.tex), so i think we can close this issues also and I don't know if you accept suggestions but it would be fine if you supported generating the strings in .po format because it would be easier to upload to a translation platform.

thank you very much for your help.

**Comment by u3shit** [comment]
The output is currently is either what the old strtool or what used, or the custom lua, but at it's current form it's probably more suited for debugging than actual usage. I don't think PO files would be a good choice, because after importing old text entries are lost, so you wouldn't be able to match up the original strings with the translations in a second import. Some other format that use keys instead of strings would be better, but I don't know any widespread format of this kind. Plus this project is pretty much on life support right now, so don't expect any big developments.
