### ISSUE TITLE
CL3 can has endianess

### ISSUE THREAD

**Issue by clienthax** [u3shit/neptools#6]
CL3B = big endian
CL3L= small endian
Found in vita version of Genkai Tokki: Moero Crystal 
gbin doesnt seem to be in big endian in this game but i notice there is a L at the end of the magic, potentially the same applies there

![image](https://cloud.githubusercontent.com/assets/1056270/22394275/6c468b22-e513-11e6-80ae-7175c2eb6c25.png)

**Comment by u3shit** [comment]
Yeah, I had a feeling that `L` corresponds to little-endian, but since I didn't find any big-endian file I couldn't confirm it.

Could you send some sample files to check it? I don't have a vita.

**Comment by clienthax** [comment]
https://drive.google.com/drive/u/0/folders/0Bx0UOdXvMrqfandmR2stRGNVYmc

**Comment by u3shit** [comment]
Weird. Cl3 is big endian, stcm/gbin little. 

Anyway it looks like there are other differences too as the gbin files give errors too. I might look into it, but non-nep games are not really a priority right now.

**Comment by clienthax** [comment]
@u3shit yeah, the gbins are also utf8 which broke your detection as field 30 was 4
I have a bodged up fork that works fine for crystal currently

**Comment by u3shit** [comment]
I have modified Neptools to handle both little and big endian CL3s, but now it looks horrible. I'll think about a better solution before pushing it online...

About the gbins: that field was 4 in the Re;Births which used Shift-JIS, and 8 in Neptunia VII which is UTF-8.  Now it looks like crystal still has field_30 set to 4 while using UTF-8. So ATM I have no idea how to reliably detect it...

Looks like there problem with gbins are restricted to `000001.gbin` and `000002.gbin`. They're probably corrupted, but since they contain mixed English and Japanese text while others only Japanese, they probably unused.
